#include <stdio.h>
#include <stdlib.h>

// Your binary-safe encoding function
void obfs_encode_binary(unsigned char key, unsigned char *data, size_t len) {
    unsigned char curr_key;
    for (size_t i = 0; i < len; i++) {
        curr_key = key * (i + 1);
        while (curr_key == 0 || curr_key == 10 || (curr_key >= 32 && curr_key <= 126)) {
            curr_key += 47;
        }
        data[i] = data[i] ^ curr_key;
        key = curr_key;
    }
}

int main(int argc, char *argv[]) {
    // We expect the user to pass the input file (raw_payload.bin)
    if (argc != 3) {
        printf("Usage: %s <raw_payload.bin> <key>\n", argv[0]);
        return 1;
    }

    unsigned char DECKEY = atoi(argv[2]);

    // 1. Open the raw binary file
    FILE *infile = fopen(argv[1], "rb");
    if (!infile) {
        printf("[-] Could not open input file!\n");
        return 1;
    }

    // 2. Find out how big the file is
    fseek(infile, 0, SEEK_END);
    size_t file_size = ftell(infile);
    rewind(infile);

    // 3. Read the file into memory
    unsigned char *buffer = (unsigned char *)malloc(file_size);
    fread(buffer, 1, file_size, infile);
    fclose(infile);

    // 4. Encode the payload in memory
    obfs_encode_binary(DECKEY, buffer, file_size);

    // 5. GENERATE THE NEW HEADER FILE
    FILE *outfile = fopen("payload.h", "w");
    if (!outfile) {
        printf("[-] Could not create payload.h!\n");
        free(buffer);
        return 1;
    }

    fprintf(outfile, "// AUTO-GENERATED BY ENCODER - DO NOT EDIT MANUALLY\n");
    fprintf(outfile, "#ifndef PAYLOAD_H\n#define PAYLOAD_H\n#include <stddef.h>\n\n");
    fprintf(outfile, "size_t payload_size = %zu;\n\n", file_size);
    fprintf(outfile, "unsigned char payload[] = {\n    ");

    // Write the encrypted bytes as a C array
    for (size_t i = 0; i < file_size; i++) {
        fprintf(outfile, "0x%02X", buffer[i]);
        if (i < file_size - 1) fprintf(outfile, ", ");
        if ((i + 1) % 12 == 0 && i < file_size - 1) fprintf(outfile, "\n    ");
    }

    fprintf(outfile, "\n};\n\n#endif // PAYLOAD_H\n");
    fclose(outfile);
    free(buffer);

    printf("[+] Successfully generated 'payload.h' with %zu encoded bytes!\n", file_size);
    return 0;
}